import { programs, runsFor, TEACHER_TRAINING_URL, INCOME_RANGES, TEACHER_TRAINING_PLANS, emptyApplication, sampleApplication, assessment, money, validateStep, guidance } from './model.js';
const $ = (id) => document.getElementById(id);
const escape = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key = 'cfa-scholarship-preview-v3';
const now = new Date();
const today = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
let state = { application: emptyApplication(), step: 0, submitted: false, history: [] };
try { const saved = JSON.parse(sessionStorage.getItem(key)); if (saved?.application && Number.isInteger(saved.step) && saved.step >= 0 && saved.step < 4 && Array.isArray(saved.history)) state = saved; } catch { /* Storage is optional for the demo. */ }
let storageWorks = true;
function save() { try { sessionStorage.setItem(key, JSON.stringify(state)); storageWorks = true; } catch { storageWorks = false; } $('save-status').textContent = storageWorks ? 'Example saved in this tab.' : 'Browser storage is unavailable. Keep this page open to retain your example.'; }
function show(view) { ['welcome','application','submitted','review'].forEach(id => $(id).hidden = id !== view); const reviewing = view === 'review'; $('reviewer-tab').classList.toggle('active', reviewing); $('applicant-tab').classList.toggle('active', !reviewing); $('reviewer-tab').setAttribute('aria-pressed', String(reviewing)); $('applicant-tab').setAttribute('aria-pressed', String(!reviewing)); if(view === 'welcome') $('resume').hidden = !state.application.name; }
const input = (name, label, type = 'text', attrs = '') => `<label for="field-${name}">${label}</label><input id="field-${name}" name="${name}" type="${type}" value="${escape(state.application[name])}" ${attrs}/>`;
const textarea = (name, label) => `<label for="field-${name}">${label}</label><textarea id="field-${name}" name="${name}" maxlength="3000">${escape(state.application[name])}</textarea>`;
const select = (name, label, choices) => `<label for="field-${name}">${label}</label><select id="field-${name}" name="${name}" required><option value="" ${state.application[name] ? '' : 'selected'} disabled>Choose one…</option>${choices.map(c => `<option ${state.application[name] === c ? 'selected' : ''}>${escape(c)}</option>`).join('')}</select>`;
const orNone = (v, f = (x) => x) => v === '' || v == null ? 'Not provided' : f(v);
const details = (rows) => `<dl class="detail-list">${rows.map(([label,value]) => `<div><dt>${escape(label)}</dt><dd>${escape(value)}</dd></div>`).join('')}</dl>`;
const chosen = (a) => { const program = programs.find(p => p.id === a.program); return { program, run: program ? runsFor(a.program, today).find(r => r.id === a.run) : null }; };
function summary() { const a = state.application; const { program, run } = chosen(a); const calc = assessment(a, a.tuition); return details([['Name',a.name],['School / organization',a.school || 'Not provided'],['Program',program?.name || 'Not selected'],['Applying for',run ? (run.id === 'next' ? 'A future session or cohort' : run.dates) : 'Not selected'],['Program cost',a.tuition === '' ? 'Not provided' : money(a.tuition)],['Monthly contribution',a.monthly === '' ? 'Not provided' : money(a.monthly)],['Number of months',a.months],['Confirmed outside support',a.support === '' ? 'Not provided' : money(a.support)],['Annual family income',orNone(a.income)],['People in the family',orNone(a.household)],['Estimated annual expenses',orNone(a.expenses, money)],['Estimated family assets',orNone(a.assets, money)],['Plans Waldorf teacher training',orNone(a.teacherTraining)],['Minimum aid hoped for',orNone(a.minimumAid, money)],['Remaining funding gap',calc ? money(calc.gap) : 'More information needed']]) + `<h3 style="margin-top:24px">Anything else you shared</h3><p class="long-answer">${escape(a.circumstances || 'Not provided')}</p>`; }
function programFields(a) {
  const { program } = chosen(a);
  const options = programs.map(p => `<option value="${p.id}" ${a.program === p.id ? 'selected' : ''}>${escape(p.name)}</option>`).join('');
  let html = `<label for="field-program">Program</label><select id="field-program" name="program" required><option value="" ${a.program ? '' : 'selected'} disabled>Choose a program…</option>${options}</select>`;
  const ttNote = `<div class="review-notice"><strong>Applying for teacher training?</strong><p>Antioch Waldorf Teacher Training, WHiSTEP and TSHE are multi-year programs with their own application. <a href="${TEACHER_TRAINING_URL}">Use the Teacher Training application</a>.</p></div>`;
  if (!program) return html + '<p class="muted">Programs and dates come from CfA’s program calendar.</p>' + ttNote;
  const runs = runsFor(a.program, today);
  html += `<fieldset class="runs"><legend>Which dates are you applying for?</legend>${runs.map(r => `<label class="run"><input type="radio" name="run" value="${r.id}" ${a.run === r.id ? 'checked' : ''} required /><span><strong>${escape(r.id === 'next' ? r.label : r.dates)}</strong>${r.id === 'next' ? '' : `<br /><span class="muted">${escape(r.label.split(' · ')[0])}${r.format ? ` · ${escape(r.format)}` : ''}</span>`}<br /><span class="run-status">${escape(r.status)}</span></span></label>`).join('')}</fieldset><p class="muted">Dates from CfA’s <a href="/calendar" target="_blank" rel="noopener">program calendar</a>. <a href="${program.href}" target="_blank" rel="noopener">About ${escape(program.name)}</a>.</p>`;
  return html + ttNote;
}
function render(focus = false) {
  const a = state.application;
  const titles = ['First, let’s get acquainted.','What would feel manageable?','A few questions about your household.','Does this look right?'];
  const guides = ['Use a fictional name as you explore. In the live version, your verified email will let you return to this application.',guidance(a),'These are the same questions CfA’s current financial aid forms ask. Estimates are fine, and you can ask to speak with someone instead.','You can go back and correct anything. Your reasons for taking the course provide context; this preview does not score your writing.'];
  $('step-count').textContent = `Step ${state.step + 1} of 4`;
  $('step-title').textContent = titles[state.step]; $('guide-text').textContent = guides[state.step];
  document.querySelectorAll('#steps li').forEach((el,i) => { el.classList.toggle('current',i===state.step); if(i===state.step) el.setAttribute('aria-current','step'); else el.removeAttribute('aria-current'); });
  $('back').hidden = state.step === 0; $('next').textContent = state.step === 3 ? 'Submit example →' : 'Continue →'; $('form-error').textContent = '';
  if(state.step === 0) $('fields').innerHTML = input('name','Your name','text','required maxlength="120" autocomplete="off"') + input('school','School or organization (optional)','text','maxlength="200" autocomplete="off"') + programFields(a);
  if(state.step === 1) { const { program } = chosen(a); $('fields').innerHTML = input('tuition','Program cost you are applying for help with (USD)','number','min="1" max="100000" step="0.01" required') + `<p class="muted">Use the cost on the <a href="${program.href}" target="_blank" rel="noopener">${escape(program.name)} page</a> for the dates you chose.</p><div class="field-row"><div>${input('monthly','What could you contribute each month?','number','min="0" max="100000" step="0.01" required')}</div><div>${input('months','Over how many months?','number','min="1" max="24" step="1" required')}</div></div>` + input('support','Confirmed support from your school or elsewhere (total)','number','min="0" max="1000000" step="0.01" required') + '<p class="muted">Enter 0 if none. A proposed payment schedule is subject to CfA’s review.</p>'; }
  if(state.step === 2) $('fields').innerHTML = select('income','Your annual family income',INCOME_RANGES) + `<div class="field-row"><div>${input('household','How many in the family? (optional)','number','min="1" max="50" step="1"')}</div><div>${input('expenses','Estimated annual expenses (optional)','number','min="0" max="10000000" step="1"')}</div></div><div class="field-row"><div>${input('assets','Estimated value of family assets (optional)','number','min="0" max="100000000" step="1"')}</div><div>${input('minimumAid','Minimum financial aid you hope for (optional)','number','min="0" max="100000" step="0.01"')}</div></div>` + select('teacherTraining','Do you intend to pursue Waldorf teacher training?',TEACHER_TRAINING_PLANS) + textarea('circumstances','Anything else you wish to share in support of your request? (optional)') + '<p class="muted">No uploads, tax returns or account numbers on this form.</p>';
  if(state.step === 3) $('fields').innerHTML = summary() + `<label><input name="confirmed" type="checkbox" ${a.confirmed ? 'checked' : ''} required />I have reviewed these fictional answers.</label>`;
  if(focus) $('step-title').focus();
}
$('application-form').addEventListener('input',event=>{ const target=event.target; if(!target.name || !(target.name in state.application)) return; state.application[target.name] = target.type === 'checkbox' ? target.checked : target.value; if(target.name !== 'confirmed') state.application.confirmed = false; if(target.name === 'program') { state.application.run = ''; render(); $('field-program').focus(); } save(); if(state.step===1) $('guide-text').textContent = guidance(state.application); });
$('application-form').addEventListener('submit',event=>{ event.preventDefault(); const error=validateStep(state.application,state.step,today); if(error) { $('form-error').textContent=error; return; } if(state.step<3) { state.step++; save(); render(true); } else { state.submitted=true; state.history.push({at:new Date().toISOString(),text:'Applicant submitted this fictional example.'}); save(); show('submitted'); } });
$('back').onclick=()=>{state.step--;save();render(true);};
$('demo-login').onsubmit=event=>{event.preventDefault();$('demo-login').hidden=true;$('demo-verify').hidden=false;$('demo-code').focus();};
$('demo-verify').onsubmit=event=>{event.preventDefault(); if($('demo-code').value!=='123456') { $('login-status').textContent='For this simulation, use 123456.'; return; } $('login-status').textContent='';show(state.submitted?'submitted':'application');render(true);};
$('resume').onclick=()=>{show(state.submitted?'submitted':'application');render(true);};
$('save-exit').onclick=()=>{save();show('welcome');};
$('applicant-tab').onclick=()=>show('welcome');
$('reviewer-tab').onclick=()=>{show('review');renderReview();};
$('see-review').onclick=()=>{show('review');renderReview();};
$('edit-example').onclick=()=>{state.submitted=false;delete state.decision;state.application.confirmed=false;state.step=0;save();show('application');render(true);};
$('load-sample').onclick=()=>{state={application:sampleApplication(),step:3,submitted:true,history:[{at:new Date().toISOString(),text:'Fictional example loaded for staff review.'}]};save();renderReview();};
$('reset').onclick=()=>{state={application:emptyApplication(),step:0,submitted:false,history:[]};save();$('demo-login').hidden=false;$('demo-verify').hidden=true;$('demo-code').value='';$('login-status').textContent='';show('welcome');};
function renderReview() {
  const a=state.application; const calc=assessment(a,a.tuition); const { program, run } = chosen(a);
  if(!state.submitted) { $('review-content').innerHTML='<div class="card"><h2>No submitted example yet.</h2><p>Complete the applicant walkthrough, or choose “Load fictional example” above to explore a completed application.</p></div>';return; }
  $('review-content').innerHTML = `<span class="badge">${escape(state.decision || 'Awaiting human review')} · simulation</span><h2>${escape(a.name)}</h2><p class="muted">${escape(program?.name || '')}${run ? ` · ${escape(run.id === 'next' ? 'future session or cohort' : run.dates)} (${escape(run.status)})` : ''}${program ? ` · <a href="${program.href}" target="_blank" rel="noopener">program page</a>` : ''}</p>${calc ? `<div class="stats"><div class="stat"><span>Program cost</span><strong>${money(calc.tuition)}</strong></div><div class="stat"><span>Contribution + support</span><strong>${money(calc.contribution+calc.support)}</strong></div><div class="stat gap"><span>Remaining funding gap</span><strong>${money(calc.gap)}</strong></div></div>` : ''}<div class="review-grid"><div class="card"><h3>Applicant’s answers</h3>${summary()}</div><div><div class="card"><p class="eyebrow">Calculation for review</p><h3>A clear starting point.</h3><p>${calc ? `The applicant proposes ${money(calc.contribution)} in personal payments plus ${money(calc.support)} in confirmed outside support. That leaves ${money(calc.gap)} to discuss.` : 'More information is needed to calculate the gap.'}</p><p class="muted">This is an arithmetic funding gap, not an approved award or a finding of eligibility. Available funds, eligibility rules, program admission, and the proposed payment term still need human review.</p><p class="muted">No approved rubric is loaded. There is no AI-generated recommendation in this version.</p><form id="decision-form"><label for="decision">Example review action</label><select id="decision" required><option value="Request more information">Request more information</option><option value="Recommend an award">Recommend an award</option><option value="Refer for exception review">Refer for exception review</option><option value="Decline with explanation">Decline with explanation</option></select><label for="award">Proposed award (USD; required for an award recommendation)</label><input id="award" type="number" min="0" max="${calc?.tuition||0}" step="0.01" /><label for="reason">Reason / next step</label><textarea id="reason" required maxlength="2000" placeholder="Explain the decision and any questions to resolve."></textarea><button class="primary" type="submit">Record example review</button><p id="decision-error" class="error" role="alert"></p></form></div><div class="card" style="margin-top:20px"><h3>Review history</h3><ol class="audit">${state.history.map(h=>`<li><strong>${escape(new Date(h.at).toLocaleString())}</strong><br />${escape(h.text)}</li>`).join('')}</ol><p class="small">Demo history stays in this tab. No award, email, enrollment, or accounting entry is created.</p></div></div></div>`;
  $('decision').onchange=()=>{$('award').required=$('decision').value==='Recommend an award';};
  $('decision-form').onsubmit=event=>{event.preventDefault();const decision=$('decision').value;const reason=$('reason').value.trim();const award=$('award').value; if(!reason || (decision==='Recommend an award' && (award===''||Number(award)<=0))) { $('decision-error').textContent='Please provide a reason and, for an award recommendation, a positive amount.';return; } state.decision=decision;state.history.push({at:new Date().toISOString(),text:`${decision}${decision==='Recommend an award'?` of ${money(award)}`:''}. ${reason}`});save();renderReview();};
}
show('welcome');
